version: '3'

services:
  kelpie-worker:
    image: saladtechnologies/kelpie-demo:latest
    build:
      context: .
      dockerfile: Dockerfile.kelpie
    environment:
      # This is how high the job should count. It's part of
      # the job's normal functioning
      - MAX_COUNT=10

      # These are the environment variables that Kelpie needs
      - KELPIE_API_URL=https://kelpie.saladexamples.com
      - KELPIE_API_KEY

      # These are the environment variables that are needed
      # to access s3-compatible storage
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION

      # If you're using R2 or Wasabi, you'll need to set
      # the endpoint URL
      - AWS_ENDPOINT_URL

      # In production, these environment variables are set
      # automatically by Salad's infrastructure.
      - SALAD_CONTAINER_GROUP_ID=local-test
      - SALAD_MACHINE_ID=local-test
      
